vega/investingsite/urls.py
from django.urls import path

from . import views

app_name = 'investingsite'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:pk>/', views.DetailView.as_view(), name='detail'),
]

vega/vega/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('investingsite/', include('investingsite.urls')),
]

vega/investingsite/models.py
import random

from django.db import models


class Stock(models.Model):
    random.seed(a=None, version=2)
    stock_id = models.CharField(primary_key=True, max_length=20, default='UNDEFINED')
    name = models.CharField(max_length=100)
    ticker = models.CharField(max_length=10)
    price = models.DecimalField(decimal_places=3, max_digits=100, default=0)
    earnings = models.DecimalField(decimal_places=3, max_digits=100, default=0)
    shares_outstanding = models.BigIntegerField(default=1)
    total_assets = models.DecimalField(decimal_places=3, max_digits=100, default=0)
    total_liabilities = models.DecimalField(decimal_places=3, max_digits=100, default=0)
    preferred_equity = models.DecimalField(decimal_places=3, max_digits=100, default=0)
    currency = models.DecimalField(decimal_places=3, max_digits=100, default=0)

    def __str__(self):
        return self.name

    def price_to_earnings(self):
        try:
            return self.price / Stock.earnings_per_share(self)
        except ZeroDivisionError as err:
            print('Handling run-time error:', err)
            pass

    def earnings_per_share(self):
        try:
            return self.earnings / self.shares_outstanding
        except ZeroDivisionError as err:
            print('Handling run-time error:', err)
            pass

    def price_to_book(self):
        try:
            return self.price / Stock.book_value_per_share(self)
        except ZeroDivisionError as err:
            print('Handling run-time error:', err)
            pass

    def book_value_per_share(self):
        try:
            return Stock.book_value(self) / self.shares_outstanding
        except ZeroDivisionError as err:
            print('Handling run-time error:', err)
            pass

    def book_value(self):
        return self.total_assets - self.total_liabilities - self.preferred_equity

    def debt_to_equity(self):
        try:
            return self.total_liabilities / Stock.shareholder_equity(self)
        except (ZeroDivisionError) as err:
            print('Handling run-time error:', err)
            pass

    def shareholder_equity(self):
        return self.total_assets - self.total_liabilities

vega/investingsite/views.py
from datetime import timezone

from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.views import generic

from .models import Stock


class IndexView(generic.ListView):
    template_name = 'investingsite/index.html'
    context_object_name = 'stock_list'

    def get_queryset(self):
        return Stock.objects.all()


class DetailView(generic.DetailView):
    model = Stock
    context_object_name = 'stock'
    template_name = 'investingSite/stockDetails.html'

    def get_queryset(self):
        return Stock.objects.filter(stock_id=self.kwargs['pk'])

vega/investingsite/templates/investingSite/index.html
<!DOCTYPE html>

{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

<html>
  <head>
    <meta charset="utf-8">
    <title>Stonks</title>
  </head>
  <body>
      <table class="table table-dark">
        <thead>
        <tr>
      <th scope="col">Ticker</th>
      <th scope="col">Name</th>
      <th scope="col">Stuff</th>
        </tr>
        </thead>
        <tbody>
    {% for stock in stock_list %}
        <tr>
          <th scope="row">{{ stock.ticker }}</a></th>
          <td><a href="{% url 'investingsite:detail' stock.stock_id %}">{{ stock.name }}</a></td>
        </tr>
    {% endfor %}
        </tbody>
      </table>
  </body>
</html>

vega/investingsite/templates/investingSite/stockDetails.html
<!DOCTYPE html>

{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

<html>
  <head>
    <meta charset="utf-8">
    <title>Stokks</title>
  </head>
  <body>
    <div class="col-sm-6">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-dark mb-0">
                <thead>
                    <tr>
                        <th scope="row">Blank?</th>
                        <th scope="col">2015</th>
                        <th scope="col">2016</th>
                        <th scope="col">2017</th>
                        <th scope="col">2018</th>
                        <th scope="col">2019</th>
                        <th scope="col">YTD</th>
                        <th scope="col">5 Year sum</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                      <th scope="row">P/E</a></th>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                    </tr>
                    <tr>
                      <th scope="row">P/B</a></th>
                        <td><a href="#" class="card-link">{{ stock.price_to_book }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_book }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_book }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_book }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_book }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_book }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_book }}</a></td>
                    </tr>
                    <tr>
                      <th scope="row">D/E</a></th>
                        <td><a href="#" class="card-link">{{ stock.debt_to_equity }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.debt_to_equity }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.debt_to_equity }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.debt_to_equity }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.debt_to_equity }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.debt_to_equity }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.debt_to_equity }}</a></td>
                    </tr>
                    <tr>
                      <th scope="row">FCF</a></th>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                    </tr>
                    <tr>
                      <th scope="row">PEG</a></th>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                        <td><a href="#" class="card-link">{{ stock.price_to_earnings }}</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
  </body>
</html>